-- load_sbsa.sql  ·  Standard Bank SD (BDSP) programme — UPDATE onto existing sponsor 'Standard Bank ' (4e401d68-a1e5-4b74-9a67-1ce9511569e4).
-- 4 new beneficiaries (VB Shopfitters, Mandla Lighting, Sintra Creative, S&K Panel Beaters) loaded fresh.
-- 2 existing (Hearts & Flowers, Leras Events) reconciled in place: reopened to active, RAG/notes refreshed,
-- missing Annexure-B line added, monthly Status-Log updates appended. 2 open escalations raised with SBSA ESD.
-- Owner/PM: Boitumelo Matobela; escalations raised by Rinaldo Josie. CTE + gen_random_uuid (no literal row UUIDs).
begin;

-- SB-001  VB Shopfitters  [On Hold -> implementation, red, 5 lines]
with b as (
  insert into beneficiaries (name,sponsor_id,industry,contact_person,contact_email,contact_phone,directors,stage,lifecycle,project_manager_id,budget,outstanding_items,rag_override,rag_override_reason,cycle,last_engagement_at,created_at) values (
    'VB Shopfitters','4e401d68-a1e5-4b74-9a67-1ce9511569e4','Shopfitting & Retail Interiors','Suveer Bridglall (Manager)','ops@vbshopfitters.com','078 351 4734','[]'::jsonb,'implementation','active','8957f6bb-9b23-4412-9c14-d25d3e2088de',116957.0,'CIPC documents delayed by the deceased estate process. Letter of Executorship received - Sanlam Trust appointed as representative, shared with SBSA. No feedback from the legal team.','red'::rag,'Director deceased; company ownership transfer not finalised. Delivery risk rated HIGH in the July 2026 report. CIPC documents outstanding pending the estate. Agreement signatory is the deceased director.',1,null,'2026-01-16') returning id)
, iv0 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Brand Builder','other',22115.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R22,115. Discovery session and questionnaire; 1 logo concept (2 refinement rounds); colour palette, typography and brand usage guide; visual identity manual with print-ready and digital assets (AI, PNG, JPG, SVG, PDF) All VB Shopfitters delivery suspended pending the estate.','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'All VB Shopfitters delivery suspended pending the estate.','na','2026-01-16',true,now(),'2026-01-16',1 from b returning id)
, iv1 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Stationery Pack','other',35229.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R35,229. Branded letterhead, email signature, business cards and quotation templates; redesign of company profile using new branding and professional layout','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'Director deceased; company ownership transfer not finalised. Delivery risk rated HIGH in the July 2026 report. CIPC documents outstanding pending the estate. Agreement signatory is the deceased director.','na','2026-01-16',true,now(),'2026-01-16',1 from b)
, iv2 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Standard 5-Page Corporate Website','other',18075.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R18,075. Professional, responsive website optimised for SEO and mobile; About, Services, Portfolio, Clients and Contact pages','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'Director deceased; company ownership transfer not finalised. Delivery risk rated HIGH in the July 2026 report. CIPC documents outstanding pending the estate. Agreement signatory is the deceased director.','na','2026-01-16',true,now(),'2026-01-16',1 from b)
, iv3 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Google Ads Management (Growth - 2 months)','other',41538.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R41,538. Campaign management and Google Ads optimisation for measurable lead generation; account setup, keyword targeting, up to 4 campaigns; A/B testing and monthly insights Ad spend up to R15,000 included for the two months.','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'Ad spend up to R15,000 included for the two months.','na','2026-01-16',true,now(),'2026-01-16',1 from b)
, iv4 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Business Coaching (Initial 2 Sessions)','other',0.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R0. Two strategic planning sessions on structure, goal setting and leadership balance No fee.','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'No fee.','na','2026-01-16',true,now(),'2026-01-16',1 from b)
, wu as (
  insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Remains on hold. Letter of Executorship received; Sanlam Trust appointed as the representative and the document has been shared with Standard Bank. CIPC documents still delayed by the estate process, with no feedback from the legal team.','Confirm with SBSA whether the programme continues under the Sanlam Trust representation or moves to close-out','Rinaldo Josie','2026-07-31'::timestamptz from iv0 returning 1)
, e as (
  insert into escalations (intervention_id,beneficiary_id,reason,context,status,current_owner_id,current_owner_role,consultant_id,manco_id,sponsor_id,participants,raised_by,raised_at,last_action_at)
  select null,b.id,'Risk: Delivery / Business Continuity','[HIGH risk] Business continuity at risk following the passing of the owner. Company ownership transfer not finalised; CIPC documents delayed by the estate process. The agreement signatory is the deceased director. Mitigation: Letter of Executorship received. The appointed representative is the Sanlam Trust. Document shared with Standard Bank.','with_sponsor',null,'external','8957f6bb-9b23-4412-9c14-d25d3e2088de','69effdfb-6c59-4138-94a4-ea037030a1ec',null,array['8957f6bb-9b23-4412-9c14-d25d3e2088de','69effdfb-6c59-4138-94a4-ea037030a1ec']::uuid[],'69effdfb-6c59-4138-94a4-ea037030a1ec','2026-07-31','2026-07-31' from b returning id)
insert into escalation_events (escalation_id,at,user_id,kind,to_status,text)
  select id,'2026-07-31','69effdfb-6c59-4138-94a4-ea037030a1ec','raised','with_sponsor','Risk: Delivery / Business Continuity: [HIGH risk] Business continuity at risk following the passing of the owner. Company ownership transfer not finalised; CIPC documents delayed by the estate process. The agreement signatory is the deceased director. Mitigation: Letter of Executorship received. The appointed representative is the Sanlam Trust. Document shared with Standard Bank.' from e;

-- SB-002  Mandla Lighting  [Off-Boarding -> implementation, red, 3 lines]
with b as (
  insert into beneficiaries (name,sponsor_id,industry,contact_person,contact_email,contact_phone,directors,stage,lifecycle,project_manager_id,budget,outstanding_items,rag_override,rag_override_reason,cycle,last_engagement_at,created_at) values (
    'Mandla Lighting','4e401d68-a1e5-4b74-9a67-1ce9511569e4','Electrical & Lighting','Jeremia (Jerry) Mandla Mpofu','jerry@mandlalighting.co.za','011 873 3982','[]'::jsonb,'implementation','active','8957f6bb-9b23-4412-9c14-d25d3e2088de',67915.0,'Signature block is blank in the copy on file. B-BBEE certificate was not among the documents supplied.','red'::rag,'Awaiting SBSA ESD confirmation of the off-boarding process. Director ill since March 2026; requested on 29 June 2026 that the programme be put on hold until further notice, noting cancellation may be necessary. UCA acknowledged and initiated off-boarding on 16 July 2026. No representative nominated despite three requests.',1,null,'2026-07-31') returning id)
, iv0 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Financial Management & Governance Support','other',45800.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R45,800. Cloud-based accounting system (Xero or Sage) with monthly management accounts, reconciliations and tax oversight; one-on-one budgeting session to forecast cash flow Largest single intervention in the cohort. Suspended on the director’s written request.','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'Largest single intervention in the cohort. Suspended on the director’s written request.','na','2026-07-31',true,now(),'2026-07-31',1 from b returning id)
, iv1 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Brand Builder','other',22115.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R22,115. Discovery session and questionnaire; 1 logo concept (2 refinement rounds); colour palette, typography and brand usage guide; visual identity manual with print-ready and digital assets','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'Awaiting SBSA ESD confirmation of the off-boarding process. Director ill since March 2026; requested on 29 June 2026 that the programme be put on hold until further notice, noting cancellation may be necessary. UCA acknowledged and initiated off-boarding on 16 July 2026. No representative nominated despite three requests.','na','2026-07-31',true,now(),'2026-07-31',1 from b)
, iv2 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Business Coaching (Initial 2 Sessions)','other',0.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R0. Two strategic planning sessions on structure, goal setting and leadership balance No fee.','8957f6bb-9b23-4412-9c14-d25d3e2088de','on_hold',null,'No fee.','na','2026-07-31',true,now(),'2026-07-31',1 from b)
, wu as (
  insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Remains on hold. The director has submitted a formal written request to be removed from the programme and for all communication to cease, to focus on his health. No representative appointed. July report records that the beneficiary needs to be removed from the programme.','Obtain SBSA ESD''s decision on removal and prepare the close-out pack','Rinaldo Josie','2026-07-31'::timestamptz from iv0
  union all
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Director wrote on 29 June 2026 requesting the programme be put on hold until further notice, citing health and an unstable business, and noting cancellation may be necessary. UCA acknowledged on 16 July 2026 and confirmed it would action off-boarding. Three requests to nominate a representative - 9 April, 26 May and 22 June - remain unanswered.','Obtain SBSA ESD confirmation of the off-boarding process, then remove from reporting and billing','Rinaldo Josie','2026-08-06'::timestamptz from iv0 returning 1)
, e as (
  insert into escalations (intervention_id,beneficiary_id,reason,context,status,current_owner_id,current_owner_role,consultant_id,manco_id,sponsor_id,participants,raised_by,raised_at,last_action_at)
  select null,b.id,'Escalation: Off-Boarding','[HIGH risk] Director ill since March 2026. On 29 June 2026 he wrote asking for the programme to be put on hold until further notice, citing his health and an unstable business, and noted that cancellation may be necessary. UCA acknowledged on 16 July 2026 and confirmed it would action the off-boarding process. UCA had asked on 9 April, 26 May and 22 June whether a representative could be nominated; that remains unanswered. Mitigation: Request recorded and acknowledged. Off-boarding initiated by UCA. Now awaiting SBSA ESD confirmation of the off-boarding process before the beneficiary is removed from reporting and billing.','with_sponsor',null,'external','8957f6bb-9b23-4412-9c14-d25d3e2088de','69effdfb-6c59-4138-94a4-ea037030a1ec',null,array['8957f6bb-9b23-4412-9c14-d25d3e2088de','69effdfb-6c59-4138-94a4-ea037030a1ec']::uuid[],'69effdfb-6c59-4138-94a4-ea037030a1ec','2026-06-29','2026-06-29' from b returning id)
insert into escalation_events (escalation_id,at,user_id,kind,to_status,text)
  select id,'2026-06-29','69effdfb-6c59-4138-94a4-ea037030a1ec','raised','with_sponsor','Escalation: Off-Boarding: [HIGH risk] Director ill since March 2026. On 29 June 2026 he wrote asking for the programme to be put on hold until further notice, citing his health and an unstable business, and noted that cancellation may be necessary. UCA acknowledged on 16 July 2026 and confirmed it would action the off-boarding process. UCA had asked on 9 April, 26 May and 22 June whether a representative could be nominated; that remains unanswered. Mitigation: Request recorded and acknowledged. Off-boarding initiated by UCA. Now awaiting SBSA ESD confirmation of the off-boarding process before the beneficiary is removed from reporting and billing.' from e;

-- SB-004  Sintra Creative  [In Delivery -> implementation, green, 2 lines]
with b as (
  insert into beneficiaries (name,sponsor_id,industry,contact_person,contact_email,contact_phone,directors,stage,lifecycle,project_manager_id,budget,outstanding_items,rag_override,rag_override_reason,cycle,last_engagement_at,created_at) values (
    'Sintra Creative','4e401d68-a1e5-4b74-9a67-1ce9511569e4','Strategic Communications & Content','Sunilkumar Dulputram Gopal','sunil@23x.co.za','072 901 3421','[]'::jsonb,'implementation','active','8957f6bb-9b23-4412-9c14-d25d3e2088de',37499.61,'None recorded','green'::rag,null,1,'2026-07-29','2026-03-27') returning id)
, iv0 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Brand Builder + Corporate Profile Development','other',22115.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R22,115. Refined business positioning; clear value proposition; professional B2B pitch asset; market positioning strategy; logo concept, colour palette and typography system; brand usage guide; full visual identity manual; digital and print-ready assets; branded letterhead, email signatures, business cards and quotation templates Reported in July 2026 as Stationery Pack completed.','8957f6bb-9b23-4412-9c14-d25d3e2088de','completed','2026-07-31',null,'na','2026-03-27',true,now(),'2026-03-27',1 from b returning id)
, iv1 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','6-page Business Profile','other',15384.61,'Category: Supplier Development (Annexure B). Fee ex-VAT R15,384.61. Redesign of the company profile into an investor- and corporate-ready format (digital and print-ready PDF); structured content aligned to industry best practice; market positioning and messaging refinement; value proposition and competitive positioning statement Reported complete in July 2026.','8957f6bb-9b23-4412-9c14-d25d3e2088de','completed','2026-07-31',null,'na','2026-03-27',true,now(),'2026-03-27',1 from b)
, wu as (
  insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Fully engaged. Two coaching sessions held on 14 and 29 July 2026 covering Commercial Execution and Sales Execution. Business Profile and Stationery Pack both completed. Assistance provided with customer negotiation.','Schedule the access to finance engagement session','Boitumelo Matobele','2026-07-31'::timestamptz from iv0 returning 1)
select 1;

-- SB-006  S&K Panel Beaters  [Onboarding -> implementation, red, 4 lines]
with b as (
  insert into beneficiaries (name,sponsor_id,industry,contact_person,contact_email,contact_phone,directors,stage,lifecycle,project_manager_id,budget,outstanding_items,rag_override,rag_override_reason,cycle,last_engagement_at,created_at) values (
    'S&K Panel Beaters','4e401d68-a1e5-4b74-9a67-1ce9511569e4','Panel Beating & Auto Repair','King Mfingwana','King@skpanelbeaters.co.za','066 189 6398','[]'::jsonb,'implementation','active','8957f6bb-9b23-4412-9c14-d25d3e2088de',48846.15,'Not on file','red'::rag,'Signature blocks and Effective Date are blank in the copy on file, yet the agreement is counted as signed in the July 2026 report. Business development approved but not started - Annexure B schedules delivery from August 2026. Entity converted from CC 2000/061678/23 to Pty Ltd 2026/095921/07. Standard Bank to complete',1,null,'2026-07-31') returning id)
, iv0 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Brand Essential','other',11538.46,'Category: Supplier Development (Annexure B). Fee ex-VAT R11,538.46. Discovery and strategic brand alignment sessions; logo redesign and visual identity system development; brand guidelines manual (colour palette, typography, tone of voice, logo usage rules); formal presentation of the completed CI Manual Business development approved in July 2026; delivery scheduled from August.','8957f6bb-9b23-4412-9c14-d25d3e2088de','not_started',null,null,'na','2026-07-31',true,now(),'2026-07-31',1 from b returning id)
, iv1 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Standard 5 Page Website (Non-E-Commerce)','other',18076.92,'Category: Supplier Development (Annexure B). Fee ex-VAT R18,076.92. Discovery on business objectives and target audience; domain registration and hosting setup; UX/UI design and content development; mobile-responsive build and cross-browser testing; SEO foundation and Google Business integration; go-live','8957f6bb-9b23-4412-9c14-d25d3e2088de','not_started',null,null,'na','2026-07-31',true,now(),'2026-07-31',1 from b)
, iv2 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Business Profile 6 Pager','other',19230.77,'Category: Supplier Development (Annexure B). Fee ex-VAT R19,230.77. Redesign of the company profile into an investor- and corporate-ready format; structured content development; market positioning and messaging refinement; clear value proposition and competitive positioning statement','8957f6bb-9b23-4412-9c14-d25d3e2088de','not_started',null,null,'na','2026-07-31',true,now(),'2026-07-31',1 from b)
, iv3 as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,completed_at,hold_reason,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,cycle)
  select id,'custom','Monitoring, Evaluation and Reporting (Ember360)','other',0.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R0. Setup of the Ember360 performance tracking dashboard; ongoing KPI monitoring; quarterly strategic review sessions; progress reporting aligned to SD Agreement requirements; corrective action planning Stated as ''Included'' in Annexure B - no separate fee. Continuous monitoring line. Starts with delivery in August 2026.','8957f6bb-9b23-4412-9c14-d25d3e2088de','not_started',null,null,'na','2026-07-31',true,now(),'2026-07-31',1 from b)
, wu as (
  insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Non-engaged; no sessions held. Business development approved: Brand Essential, Standard 5 Page Website and Business Profile 6 Pager, R48,846.15 total, scheduled to start August 2026.','Obtain the executed SD Agreement with Effective Date completed, and confirm the contracting BDSP entity name','Rinaldo Josie','2026-07-31'::timestamptz from iv0
  union all
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'All four Annexure B lines remain Not Started. Delivery scheduled to begin August 2026 per Annexure B.','Start Brand Essential delivery and obtain the executed SD Agreement with Effective Date completed','Rinaldo Josie','2026-08-06'::timestamptz from iv0 returning 1)
select 1;

-- SB-003  Hearts & Flowers  [reconcile in place: reopen + add line + updates]
update beneficiaries set lifecycle='active', stage='implementation', rag_override='amber'::rag, rag_override_reason='The revised R65,384 scope was agreed by email but never formalised in a signed Annexure B variation, which clause 16.3 requires. Committee re-approval was promised for February 2026 and has not been located.', outstanding_items='None outstanding - executed agreement now on file.' where id='ffef76a5-090f-4dc5-9f25-b0ebb788d619';
with iv as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,rag_override,rag_override_reason,cycle)
  select 'ffef76a5-090f-4dc5-9f25-b0ebb788d619','custom','Strategy and Brand Audit','other',65384.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R65,384. Strategy and brand audit forming part of the revised marketing-led scope agreed with the beneficiary in December 2025. COMBINED R65,384 value covers this line and the delivered Business Profile; the split is not documented. No signed Annexure B variation exists (flag F28).','8957f6bb-9b23-4412-9c14-d25d3e2088de','in_progress','na','2026-07-31',true,now(),'2026-07-31','amber'::rag,'The revised R65,384 scope was agreed by email but never formalised in a signed Annexure B variation, which clause 16.3 requires. Committee re-approval was promised for February 2026 and has not been located.',1
  where not exists (select 1 from interventions where beneficiary_id='ffef76a5-090f-4dc5-9f25-b0ebb788d619' and custom_name='Strategy and Brand Audit') returning id)
insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Partially engaged. One session held on 21 July 2026 covering Strategic Reset. Strategy and brand audit nearing completion; Business Profile completed. Re-engaged after non-engagement in June attributed to structural changes in the business.','Obtain the SD Agreement and Annexure B fee schedule - not on file','Rinaldo Josie','2026-07-31'::timestamptz from iv;

-- SB-005  Leras Events  [reconcile in place: reopen + add line + updates]
update beneficiaries set lifecycle='active', stage='implementation', rag_override='red'::rag, rag_override_reason='Engagement recorded as non-engaged for July', outstanding_items='Not on file' where id='e2ecdd95-f779-4a45-a0e5-b1ee93a18f7e';
with iv as (
  insert into interventions (beneficiary_id,kind,custom_name,custom_kind,custom_budget,custom_motivation,consultant_id,status,discovery_status,discovery_at,acknowledged,acknowledged_at,assigned_at,rag_override,rag_override_reason,cycle)
  select 'e2ecdd95-f779-4a45-a0e5-b1ee93a18f7e','custom','Monitoring, Evaluation and Reporting (Ember360)','other',0.0,'Category: Supplier Development (Annexure B). Fee ex-VAT R0. Continuous Ember360 monitoring line — stated as ''Included'' in Annexure B at no separate fee. Runs for the life of the engagement; never marked Delivered.','8957f6bb-9b23-4412-9c14-d25d3e2088de','in_progress','na','2026-07-31',true,now(),'2026-07-31','red'::rag,'Engagement recorded as non-engaged for July',1
  where not exists (select 1 from interventions where beneficiary_id='e2ecdd95-f779-4a45-a0e5-b1ee93a18f7e' and custom_name='Monitoring, Evaluation and Reporting (Ember360)') returning id)
insert into weekly_updates (intervention_id,author_id,completed_work,next_action,blocker_owner,created_at)
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Recorded as non-engaged with no sessions held, yet the print promo package and website were both completed in the period. Opportunity findings shared and active assistance given with RFP engagement.','Reconcile the non-engaged status against the delivery and market access activity recorded for the same month','Rinaldo Josie','2026-07-31'::timestamptz from iv
  union all
  select id,'8957f6bb-9b23-4412-9c14-d25d3e2088de'::uuid,'Brand Builder (CI Manual) confirmed delivered, closing the last open chargeable Annexure B line. All three chargeable development areas are now complete - CI Manual, website and print promo. Ember360 monitoring continues.','Itemise the CI Manual in the August deck and reconcile the non-engaged status against three completed deliverables','Rinaldo Josie','2026-08-06'::timestamptz from iv;

select (select count(*) from beneficiaries where sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4') bens,(select count(*) from interventions i join beneficiaries b on b.id=i.beneficiary_id where b.sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4') ivs,(select count(*) from escalations e join beneficiaries b on b.id=e.beneficiary_id where b.sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4') escs,(select count(*) from weekly_updates wu join interventions i on i.id=wu.intervention_id join beneficiaries b on b.id=i.beneficiary_id where b.sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4') wus;
commit;

-- ROLLBACK NOTE: this load both INSERTS (4 new benes) and UPDATES 2 existing benes in place.
-- To reverse the new beneficiaries only (VB Shopfitters, Mandla Lighting, Sintra Creative, S&K Panel Beaters):
--   delete from escalation_events where escalation_id in (select e.id from escalations e join beneficiaries b on b.id=e.beneficiary_id where b.sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4' and b.name in ('VB Shopfitters','Mandla Lighting','Sintra Creative','S&K Panel Beaters'));
--   delete from escalations where beneficiary_id in (select id from beneficiaries where sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4' and name in ('VB Shopfitters','Mandla Lighting','Sintra Creative','S&K Panel Beaters'));
--   delete from weekly_updates where intervention_id in (select i.id from interventions i join beneficiaries b on b.id=i.beneficiary_id where b.sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4' and b.name in ('VB Shopfitters','Mandla Lighting','Sintra Creative','S&K Panel Beaters'));
--   delete from interventions where beneficiary_id in (select id from beneficiaries where sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4' and name in ('VB Shopfitters','Mandla Lighting','Sintra Creative','S&K Panel Beaters'));
--   delete from beneficiaries where sponsor_id='4e401d68-a1e5-4b74-9a67-1ce9511569e4' and name in ('VB Shopfitters','Mandla Lighting','Sintra Creative','S&K Panel Beaters');
-- The 2 reconciled benes' added lines: delete from interventions where beneficiary_id in ('ffef76a5-090f-4dc5-9f25-b0ebb788d619','e2ecdd95-f779-4a45-a0e5-b1ee93a18f7e') and custom_name in ('Strategy and Brand Audit','Monitoring, Evaluation and Reporting (Ember360)');